site_name: AERO internal documentation
nav:
    - Home: index.md
    - Basic Setup: 
      - 'Wiring quickstart': 'wiring.md'
    - PX4 Reference Info:
      - 'Vehicles and Airframes': 'airframe_ref.md'
      - 'Autopilot Hardware': 'autopilot_ref.md'
      - 'Sensors': 'sensor_ref.md'
    - Software Dev:
      - 'Logging and log analysis': 'dev/log_dev.md'
      - 'Mavlink Development': 'dev/mavlink_dev.md'
theme: readthedocs

